class Const {


  static final List<String> countries = [
    "🇦🇫 Afghanistan",
    "🇦🇱 Albania",
    "🇩🇿 Algeria",
    "🇦🇸 American Samoa",
    "🇦🇩 Andorra",
    "🇦🇴 Angola",
    "🇦🇮 Anguilla",
    "🇦🇷 Argentina",
    "🇦🇲 Armenia",
    "🇦🇼 Aruba",
    "🇦🇺 Australia",
    "🇦🇹 Austria",
    "🇦🇿 Azerbaijan",
    "🇧🇸 Bahamas",
    "🇧🇭 Bahrain",
    "🇧🇩 Bangladesh",
    "🇧🇧 Barbados",
    "🇧🇾 Belarus",
    "🇧🇪 Belgium",
    "🇧🇿 Belize",
    "🇧🇯 Benin",
    "🇧🇲 Bermuda",
    "🇧🇹 Bhutan",
    "🇧🇴 Bolivia",
    "🇧🇦 Bosnia and Herzegovina",
    "🇧🇼 Botswana",
    "🇧🇷 Brazil",
    "🇮🇴 British Indian Ocean Territory",
    "🇧🇳 Brunei Darussalam",
    "🇧🇬 Bulgaria",
    "🇧🇫 Burkina Faso",
    "🇧🇮 Burundi",
    "🇰🇭 Cambodia",
    "🇨🇲 Cameroon",
    "🇨🇦 Canada",
    "🇨🇻 Cape Verde",
    "🇰🇾 Cayman Islands",
    "🇨🇫 Central African Republic",
    "🇹🇩 Chad",
    "🇨🇱 Chile",
    "🇨🇳 China",
    "🇨🇽 Christmas Island",
    "🇨🇨 Cocos (Keeling) Islands",
    "🇨🇴 Colombia",
    "🇰🇲 Comoros",
    "🇨🇬 Congo",
    "🇨🇩 Congo (Democratic Republic)",
    "🇨🇰 Cook Islands",
    "🇨🇷 Costa Rica",
    "🇭🇷 Croatia",
    "🇨🇺 Cuba",
    "🇨🇾 Cyprus",
    "🇨🇿 Czech Republic",
    "🇩🇰 Denmark",
    "🇩🇯 Djibouti",
    "🇩🇲 Dominica",
    "🇩🇴 Dominican Republic",
    "🇪🇨 Ecuador",
    "🇪🇬 Egypt",
    "🇸🇻 El Salvador",
    "🇬🇶 Equatorial Guinea",
    "🇪🇷 Eritrea",
    "🇪🇪 Estonia",
    "🇸🇿 Eswatini",
    "🇪🇹 Ethiopia",
    "🇫🇰 Falkland Islands",
    "🇫🇴 Faroe Islands",
    "🇫🇯 Fiji",
    "🇫🇮 Finland",
    "🇫🇷 France",
    "🇬🇫 French Guiana",
    "🇵🇫 French Polynesia",
    "🇬🇦 Gabon",
    "🇬🇲 Gambia",
    "🇬🇪 Georgia",
    "🇩🇪 Germany",
    "🇬🇭 Ghana",
    "🇬🇮 Gibraltar",
    "🇬🇷 Greece",
    "🇬🇱 Greenland",
    "🇬🇩 Grenada",
    "🇬🇵 Guadeloupe",
    "🇬🇺 Guam",
    "🇬🇹 Guatemala",
    "🇬🇬 Guernsey",
    "🇬🇳 Guinea",
    "🇬🇼 Guinea-Bissau",
    "🇭🇹 Haiti",
    "🇭🇳 Honduras",
    "🇭🇰 Hong Kong",
    "🇭🇺 Hungary",
    "🇮🇸 Iceland",
    "🇮🇳 India",
    "🇮🇩 Indonesia",
    "🇮🇷 Iran",
    "🇮🇶 Iraq",
    "🇮🇪 Ireland",
    "🇮🇲 Isle of Man",
    "🇮🇱 Israel",
    "🇮🇹 Italy",
    "🇯🇪 Jersey",
    "🇯🇴 Jordan",
    "🇯🇵 Japan",
    "🇰🇿 Kazakhstan",
    "🇰🇪 Kenya",
    "🇰🇮 Kiribati",
    "🇽🇰 Kosovo",
    "🇰🇼 Kuwait",
    "🇰🇬 Kyrgyzstan",
    "🇱🇦 Laos",
    "🇱🇻 Latvia",
    "🇱🇧 Lebanon",
    "🇱🇸 Lesotho",
    "🇱🇷 Liberia",
    "🇱🇾 Libya",
    "🇱🇮 Liechtenstein",
    "🇱🇹 Lithuania",
    "🇱🇺 Luxembourg",
    "🇲🇰 North Macedonia",
    "🇲🇬 Madagascar",
    "🇲🇼 Malawi",
    "🇲🇾 Malaysia",
    "🇲🇻 Maldives",
    "🇲🇱 Mali",
    "🇲🇹 Malta",
    "🇲🇭 Marshall Islands",
    "🇲🇶 Martinique",
    "🇲🇷 Mauritania",
    "🇲🇺 Mauritius",
    "🇾🇹 Mayotte",
    "🇲🇽 Mexico",
    "🇫🇲 Micronesia",
    "🇻🇺 Moldova",
    "🇲🇻 Monaco",
    "🇲🇩 Mongolia",
    "🇲🇪 Montenegro",
    "🇲🇸 Montserrat",
    "🇲🇶 Martinique",
    "🇲🇿 Mozambique",
    "🇳🇦 Namibia",
    "🇳🇷 Nauru",
    "🇳🇵 Nepal",
    "🇳🇱 Netherlands",
    "🇳🇿 New Zealand",
    "🇳🇮 Nicaragua",
    "🇳🇬 Nigeria",
    "🇳🇺 Niue",
    "🇳🇫 Norfolk Island",
    "🇰🇵 North Korea",
    "🇲🇵 Northern Mariana Islands",
    "🇳🇴 Norway",
    "🇴🇲 Oman",
    "🇵🇰 Pakistan",
    "🇵🇼 Palau",
    "🇵🇸 Palestine",
    "🇵🇦 Panama",
    "🇵🇬 Papua New Guinea",
    "🇵🇾 Paraguay",
    "🇵🇪 Peru",
    "🇵🇭 Philippines",
    "🇵🇱 Poland",
    "🇵🇹 Portugal",
    "🇶🇦 Qatar",
    "🇷🇴 Romania",
    "🇷🇺 Russia",
    "🇷🇼 Rwanda",
    "🇼🇸 Samoa",
    "🇸🇸 San Marino",
    "🇸🇿 São Tomé and Príncipe",
    "🇸🇦 Saudi Arabia",
    "🇸🇳 Senegal",
    "🇷🇸 Serbia",
    "🇸🇨 Seychelles",
    "🇸🇱 Sierra Leone",
    "🇸🇬 Singapore",
    "🇸🇮 Slovenia",
    "🇸🇧 Solomon Islands",
    "🇸🇴 Somalia",
    "🇿🇦 South Africa",
    "🇰🇷 South Korea",
    "🇸🇸 South Sudan",
    "🇪🇸 Spain",
    "🇱🇰 Sri Lanka",
    "🇸🇩 Sudan",
    "🇸🇷 Suriname",
    "🇸🇿 Eswatini",
    "🇸🇪 Sweden",
    "🇨🇭 Switzerland",
    "🇸🇾 Syria",
    "🇹🇼 Taiwan",
    "🇹🇯 Tajikistan",
    "🇹🇿 Tanzania",
    "🇹🇭 Thailand",
    "🇹🇱 Timor-Leste",
    "🇹🇬 Togo",
    "🇹🇴 Tonga",
    "🇹🇹 Trinidad and Tobago",
    "🇹🇳 Tunisia",
    "🇹🇴 Tonga",
    "🇹🇷 Turkey",
    "🇺🇲 United States",
    "🇺🇬 Uganda",
    "🇺🇦 Ukraine",
    "🇬🇧 United Kingdom",
    "🇺🇾 Uruguay",
    "🇺🇿 Uzbekistan",
    "🇻🇺 Vanuatu",
    "🇻🇦 Vatican City",
    "🇻🇪 Venezuela",
    "🇻🇳 Vietnam",
    "🇾🇪 Yemen",
    "🇿🇦 Zambia",
    "🇿🇼 Zimbabwe"
  ];
}
